SELECT
    CAST(LUTYPE AS NVARCHAR(MAX)) AS LUTYPE,
	TYPE_CODE,
	SUM(DU_TOT) AS TOT_DU
FROM mtpuser.ilut_combined2016_23_wtypecode
where type_code = 6
GROUP BY CAST(LUTYPE AS NVARCHAR(MAX)), TYPE_CODE


SELECT
    CAST(LUTYPE AS NVARCHAR(MAX)) AS LUTYPE,
	TYPE_CODE,
	SUM(DU_TOT) AS TOT_DU
FROM mtpuser.ilut_combined2040_38_wtypecode
GROUP BY CAST(LUTYPE AS NVARCHAR(MAX)), TYPE_CODE


--ilut_combined2040_38_wtypecode

SELECT DISTINCT
	CAST(LUTYPE AS NVARCHAR(MAX)) AS LUTYPE
FROM mtpuser.ilut_combined2040_38_wtypecode
WHERE CAST(LUTYPE AS NVARCHAR(MAX)) NOT IN (
	SELECT DISTINCT
		CAST(LUTYPE AS NVARCHAR(MAX)) AS LUTYPE
	FROM mtpuser.ilut_combined2016_23_wtypecode)